import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { LocalDocs, SDKPath } from '../../src/config/constants';

const sidebar: SidebarsConfig[keyof SidebarsConfig] = [
  { type: 'doc', id: 'documentation/reference/README', className: 'hidden-sidebar-item' },
  // {
  //   type: 'category',
  //   label: 'SDKs',
  //   collapsed: true,
  //   link: {
  //     type: 'generated-index',
  //     title: 'SDKs',
  //     description: 'SDKs'
  //   },
  //   items: [
  //     {
  //       type: 'category',
  //       label: 'Typescript',
  //       link: {
  //         type: 'doc',
  //         id: SDKPath('sdk/overview/README')
  //       },
  //       items: [
  //         ...buildTypeDocCategorySidebar(SDKPath('sdk/overview'), 'Overview').map((item) => (item as any).items ?? []),
  //         {
  //           type: 'category',
  //           label: 'Plugins',
  //           items: [
  //             ...buildTypeDocCategorySidebar(SDKPath('sdk/plugins/internal/anoncreds'), 'AnonCreds'),
  //             ...buildTypeDocCategorySidebar(SDKPath('sdk/plugins/internal/didcomm'), 'DIDComm'),
  //             ...buildTypeDocCategorySidebar(SDKPath('sdk/plugins/internal/dif'), 'DIF'),
  //             ...buildTypeDocCategorySidebar(SDKPath('sdk/plugins/internal/oea'), 'OEA'),
  //             ...buildTypeDocCategorySidebar(SDKPath('sdk/plugins/internal/oidc'), 'OIDC'),
  //           ]
  //         }
  //       ]
  //     },
  //     {
  //       type: 'link',
  //       label: 'Swift',
  //       href: 'https://hyperledger-identus.github.io/sdk-swift/documentation/edgeagentsdk/',
  //     },
  //     {
  //       type: 'link',
  //       label: 'Kotlin',
  //       href: 'https://hyperledger-identus.github.io/sdk-kmp/',
  //     }
  //   ]
  // },
  {
    type: 'category',
    label: 'Cloud Agent API',
    link: {
      type: 'generated-index',
      title: 'Cloud Agent API',
      description: 'OpenAPI specification for the Cloud Agent API'
    },
    items: [
      {
        type: 'autogenerated',
        dirName: LocalDocs('reference/Cloud Agent API'),
      }
    ]
  },
  LocalDocs('reference/specifications'),
  {
    type: 'link',
    label: 'PRISM DID Spec',
    href: 'https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md',
  },
  {
    type: 'category',
    label: 'Decision Records',
    link: {
      type: 'generated-index',
      title: 'Decision Records',
    },
    items: [
      {
        type: 'autogenerated',
        dirName: LocalDocs('adrs/decisions'),
      },
      {
        type: 'autogenerated',
        dirName: SDKPath('decisions'),
      },
    ]
  }
]

export default sidebar