import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { buildTypeDocCategorySidebar } from '../../src/utils';

const sidebar: SidebarsConfig[keyof SidebarsConfig] = [
  { type: 'doc', id: 'documentation/reference/README', className: 'hidden-sidebar-item' },
  {
    type: 'category',
    label: 'Typescript SDK Reference',
    link: {
      type: 'generated-index',
      title: 'Typescript SDK Reference',
      description: 'Typescript SDK Reference'
    },
    items: [
      ...buildTypeDocCategorySidebar('sdk-ts/docs/sdk/overview', 'Overview').map((item) => (item as any).items ?? []),
      {
        type: 'category',
        label: 'Plugins',
        items: [
          ...buildTypeDocCategorySidebar('sdk-ts/docs/sdk/plugins/internal/anoncreds', 'AnonCreds'),
          ...buildTypeDocCategorySidebar('sdk-ts/docs/sdk/plugins/internal/didcomm', 'DIDComm'),
          ...buildTypeDocCategorySidebar('sdk-ts/docs/sdk/plugins/internal/dif', 'DIF'),
          ...buildTypeDocCategorySidebar('sdk-ts/docs/sdk/plugins/internal/oea', 'OEA'),
          ...buildTypeDocCategorySidebar('sdk-ts/docs/sdk/plugins/internal/oidc', 'OIDC'),
        ]
      }
    ]
  },
  {
    type: 'category',
    label: 'Cloud Agent API',
    link: {
      type: 'generated-index',
      title: 'Cloud Agent API',
      description: 'OpenAPI specification for the Cloud Agent API'
    },
    items: [
      {
        type: 'autogenerated',
        dirName: 'documentation/reference/Cloud Agent API',
      }
    ]
  },
  'documentation/reference/specifications',
  {
    type: 'link',
    label: 'PRISM DID Spec',
    href: 'https://github.com/input-output-hk/prism-did-method-spec/blob/main/w3c-spec/PRISM-method.md',
  },
  {
    type: 'category',
    label: 'Decision Records',
    link: {
      type: 'generated-index',
      title: 'Decision Records',
    },
    items: [
      {
        type: 'autogenerated',
        dirName: 'documentation/adrs/decisions',
      },
      {
        type: 'autogenerated',
        dirName: 'sdk-ts/docs/decisions',
      },
    ]
  }
]

export default sidebar