branches:
  - name: 'main'
  - name: 'beta'
    prerelease: "snapshot"
  - name: gamma
    prerelease: gamma

plugins:
  - '@semantic-release/commit-analyzer'
  - [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits",
        "presetConfig": {
          "types": [
            {
              "type": "feat",
              "section": ":rocket: New Content",
              "hidden": false
            },
            {
              "type": "fix",
              "section": ":sparkles: Updates",
              "hidden": false
            },
          ]
        }
      }
    ]
  - [ '@semantic-release/changelog', { changelogFile: 'CHANGELOG.md' } ]
  - [ '@semantic-release/exec', {
    prepareCmd: 'npm version ${nextRelease.version} --git-tag-version false && ./infra/release-docs-container.sh ${nextRelease.version}',
    } ]
  - [ '@semantic-release/git', {
    assets: [ 'package.json' , 'package-lock.json', 'CHANGELOG.md' ],
    message: 'chore(release): release the Identus documentation portal ${nextRelease.version}

    ${nextRelease.notes}' } ]
  - [ "semantic-release-slack-bot", {
    notifyOnSuccess: true,
    notifyOnFail: true,
    markdownReleaseNotes: true,
    onSuccessTemplate: {
      text: "A new version of `$package_name` successfully released!\n
        Version: `$npm_package_version`\n
        Release notes:\n
        $release_notes" } } ]
