import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { mapCategories, mapStrings } from '../../src/utils';

import { default as CloudAgentSidebar } from '../../cloud-agent/docs/docusaurus/sidebars.js';


import { SidebarItemConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import { CloudAgentPath, LocalDocs } from '../../src/config/constants.js';

const tutorialsSidebar = CloudAgentSidebar.tutorialsSidebar as SidebarItemConfig[];

const sidebar: SidebarsConfig[keyof SidebarsConfig] = [
    {
        type: 'doc',
        id: 'documentation/develop/README',
        className: 'hidden-sidebar-item',
    },
    {
        type: 'link',
        label: 'Swift SDK',
        href: 'https://hyperledger-identus.github.io/sdk-swift/documentation/edgeagentsdk/',
    },
    {
        type: 'link',
        label: 'Kotlin SDK',
        href: 'https://hyperledger-identus.github.io/sdk-kmp/',
    },
    {
        type: 'category',
        label: 'Cloud Agent',
        collapsed: true,
        link: {
            type: 'generated-index',
            title: 'Cloud Agent',
            description: 'Cloud Agent'
        },
        items: [
            {
                type: 'category',
                label: 'Tutorials',
                link: {
                    type: 'doc',
                    id: CloudAgentPath('index')
                },
                items: [
                    LocalDocs('develop/quick-start'),
                    ...tutorialsSidebar.filter((i) => i !== 'index').map((i) => mapStrings(mapCategories(i)))
                ]
            },
            {
                type: 'autogenerated',
                dirName: CloudAgentPath('cloud-agent'),
            },
        ]
    },

]

export default sidebar