import fs from 'node:fs';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { getSidebarItemsForDir, mapCategories, mapStrings } from '../../src/utils';

import Sidebar from '../../cloud-agent/docs/docusaurus/sidebars.js'
import { SidebarItemConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import { CloudAgentPath, LocalDocs, SDKPath } from '../../src/config/constants.js';

const tutorialsSidebar = Sidebar.tutorialsSidebar as SidebarItemConfig[];
const converted = tutorialsSidebar
    .filter((item) => item !== 'index')
    .map((item) => mapStrings(mapCategories(item)));

const hasTutorials = fs.existsSync(SDKPath('tutorials/index.md'));

const tutorialLink = hasTutorials ?
    { type: 'doc' as const, id: SDKPath('tutorials/index') } :
    { type: 'generated-index' as const, title: 'Tutorials', description: 'Tutorials' }

const tsSidebarItems: SidebarItemConfig[] = [
    {
        type: 'category',
        label: 'Typescript',
        collapsed: true,
        link: {
            type: 'doc',
            id: SDKPath('sdk/README'),
        },
        items: [
            {
                type: 'category',
                label: 'Tutorials',
                link: tutorialLink,
                items: hasTutorials
                    ? getSidebarItemsForDir(SDKPath('tutorials')).filter((item) => !(typeof item === 'object' && item !== null && 'id' in item && item.id === SDKPath('tutorials/index')))
                    : [
                        {
                            type: 'doc',
                            id: SDKPath('examples/Backup'),
                            label: 'Backup',
                        },
                        {
                            type: 'doc',
                            id: SDKPath('pluto/README'),
                            label: "Storage - Pluto"
                        },
                        {
                            type: 'category',
                            label: 'Prism DID',
                            link: {
                                type: 'generated-index',
                                title: 'Prism DID',
                                description: 'Prism DID Related tutorials and documentation'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: SDKPath('prism'),
                                },
                            ]
                        },
                        {
                            type: 'category',
                            label: 'Connectionless & OOB',
                            link: {
                                type: 'generated-index',
                                title: 'Connectionless & OOB',
                                description: 'Connectionless & OOB'
                            },
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: SDKPath('examples/connectionless'),
                                },
                            ]
                        },
                        {
                            type: 'doc',
                            id: SDKPath('examples/SDKVerification'),
                            label: "SDK Verification"
                        },
                        {
                            type: 'doc',
                            id: SDKPath('examples/OIDC'),
                            label: "OIDC Agent (WIP)"
                        },
                    ]
            },

            {
                type: 'category',
                label: 'Migration guides',
                link: {
                    type: 'generated-index',
                    title: 'Migration guides',
                    description: 'Migration guides'
                },
                items: [
                    {
                        type: 'autogenerated',
                        dirName: SDKPath('migration'),
                    },
                ]
            }
        ]
    },
]
const sidebar: SidebarsConfig[keyof SidebarsConfig] = [
    {
        type: 'doc',
        id: 'documentation/develop/README',
        className: 'hidden-sidebar-item',
    },
    {
        type: 'category',
        label: 'SDKs',
        collapsed: true,
        link: {
            type: 'generated-index',
            title: 'SDKs',
            description: 'SDKs'
        },
        items: [
            ...tsSidebarItems,
            {
                type: 'link',
                label: 'Swift',
                href: 'https://hyperledger-identus.github.io/sdk-swift/documentation/edgeagentsdk/',
            },
            {
                type: 'link',
                label: 'Kotlin',
                href: 'https://hyperledger-identus.github.io/sdk-kmp/',
            },
        ]
    },
    {
        type: 'category',
        label: 'Cloud Agent',
        collapsed: true,
        link: {
            type: 'generated-index',
            title: 'Cloud Agent',
            description: 'Cloud Agent'
        },
        items: [
            {
                type: 'category',
                label: 'Tutorials',
                link: {
                    type: 'doc',
                    id: CloudAgentPath('index')
                },
                items: [
                    LocalDocs('develop/quick-start'),
                    ...converted
                ]
            },
            {
                type: 'autogenerated',
                dirName: CloudAgentPath('cloud-agent'),
            },
        ]
    },

]

export default sidebar