import fs from 'node:fs';
import path from 'node:path';
import type { SidebarItemConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import { projectsDocsPaths } from '../config/constants';
import { getSidebarItemsForDir } from './index';

function getSidebarPosition(filePath: string): number {
    if (!fs.existsSync(filePath)) return Infinity;
    try {
        const content = fs.readFileSync(filePath, 'utf8');
        const match = content.match(/^sidebar_position:\s*(\d+(\.\d+)?)/m);
        if (match) {
            return parseFloat(match[1]);
        }
    } catch { }
    // If it's a _category_.json
    if (filePath.endsWith('_category_.json')) {
        try {
            const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            if (typeof data.position === 'number') return data.position;
        } catch (e) {
            console.warn(`Warning: Failed to parse ${filePath}:`, e);
        }
    }
    return Infinity;
}

function resolveItemPosition(item: SidebarItemConfig, rootPath: string): number {
    if (typeof item === 'string') {
        const mdPos = getSidebarPosition(path.join(rootPath, item + '.md'));
        if (mdPos !== Infinity) return mdPos;
        return getSidebarPosition(path.join(rootPath, item + '.mdx'));
    }
    if (typeof item === 'object' && item !== null && 'type' in item) {

        // Always respect explicitly defined customProp positions universally
        if ('customProps' in item && item.customProps && typeof (item.customProps as any)?.position === 'number') {
            return (item.customProps as any).position;
        }

        if (item.type === 'doc' && item.id) {
            const mdPos = getSidebarPosition(path.join(rootPath, item.id + '.md'));
            if (mdPos !== Infinity) return mdPos;
            return getSidebarPosition(path.join(rootPath, item.id + '.mdx'));
        }
        if (item.type === 'category') {
            if (item.link && item.link.type === 'doc' && item.link.id) {
                const mdPos = getSidebarPosition(path.join(rootPath, item.link.id + '.md'));
                if (mdPos !== Infinity) return mdPos;
                return getSidebarPosition(path.join(rootPath, item.link.id + '.mdx'));
            }
            // Optional: directory level fallback
            if (Array.isArray(item.items) && item.items.length > 0) {
                // Try looking ahead at first item? Not reliable.
            }
        }
    }
    return Infinity;
}

/**
 * Abstract discovery protocol to load menu elements and sidebars from configured folders.
 * Scans all defined project documentation paths for the provided category (e.g., 'learn', 'develop').
 * Replaces Docusaurus autogenerated with custom fallback to ensure deep recursive sorting by sidebar_position.
 */
export function discoverSidebar(category: string): SidebarItemConfig[] {
    const sidebar: SidebarItemConfig[] = [];
    const rootPath = process.cwd();

    for (const projectRelPath of projectsDocsPaths) {
        const categoryRelPath = path.join(projectRelPath, category);
        const fullCategoryPath = path.join(rootPath, categoryRelPath);

        if (!fs.existsSync(fullCategoryPath)) {
            continue;
        }

        const sidebarFileTs = path.join(fullCategoryPath, 'sidebar.ts');
        const sidebarFileJs = path.join(fullCategoryPath, 'sidebar.js');

        let projectSidebar: SidebarItemConfig[] | null = null;

        // Attempt to dynamically load specifically defined subset sidebars
        if (fs.existsSync(sidebarFileTs)) {
            try {
                projectSidebar = require(sidebarFileTs).default;
            } catch (e) {
                console.error(`Error dynamically loading sidebar at ${sidebarFileTs}:`, e);
            }
        } else if (fs.existsSync(sidebarFileJs)) {
            try {
                projectSidebar = require(sidebarFileJs).default;
            } catch (e) {
                console.error(`Error dynamically loading sidebar at ${sidebarFileJs}:`, e);
            }
        }

        if (projectSidebar) {
            sidebar.push(...projectSidebar);
        } else {
            const items = fs.readdirSync(fullCategoryPath);
            if (items.length > 0) {
                const generatedItems = getSidebarItemsForDir(categoryRelPath);

                const categoryJsonPath = path.join(fullCategoryPath, '_category_.json');
                if (fs.existsSync(categoryJsonPath)) {
                    try {
                        const catProps = JSON.parse(fs.readFileSync(categoryJsonPath, 'utf8'));
                        let categoryLink = catProps.link;

                        if (categoryLink && categoryLink.type === 'doc' && categoryLink.id) {
                            let docId: string = categoryLink.id.replace(/\.mdx?$/, '');
                            if (!docId.includes('/')) docId = `${categoryRelPath}/${docId}`;
                            categoryLink = { ...categoryLink, id: docId };
                        }

                        const cleanChildItems = generatedItems.filter(item => {
                            const isIndexDoc = categoryLink && categoryLink.type === 'doc' &&
                                typeof item === 'object' && item !== null && 'type' in item && item.type === 'doc' && 'id' in item && item.id === categoryLink.id;
                            return !isIndexDoc;
                        });

                        sidebar.push({
                            type: 'category',
                            label: catProps.label || path.basename(categoryRelPath),
                            ...(catProps.collapsed !== undefined && { collapsed: catProps.collapsed }),
                            ...(catProps.collapsible !== undefined && { collapsible: catProps.collapsible }),
                            ...(catProps.className && { className: catProps.className }),
                            customProps: {
                                ...catProps.customProps,
                                ...(typeof catProps.position === 'number' && { position: catProps.position })
                            },
                            ...(categoryLink && { link: categoryLink }),
                            items: cleanChildItems
                        } as SidebarItemConfig);
                    } catch (e) {
                        console.error(`Error parsing _category_.json at ${categoryJsonPath}:`, e);
                        sidebar.push(...generatedItems);
                    }
                } else {
                    sidebar.push(...generatedItems);
                }
            }
        }
    }

    // Sort recursively based on sidebar_position frontmatter
    function sortRecursive(items: SidebarItemConfig[]) {
        items.sort((a, b) => {
            const posA = resolveItemPosition(a, rootPath);
            const posB = resolveItemPosition(b, rootPath);
            return posA - posB;
        });

        for (const item of items) {
            if (typeof item !== 'string' && (item as any).type === 'category' && Array.isArray((item as any).items)) {
                sortRecursive((item as any).items as SidebarItemConfig[]);
            }
        }
    }

    sortRecursive(sidebar);

    return sidebar;
}
