import fs from 'node:fs';
import type { SidebarItemConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

/**
 * This function builds a sidebar from a typedoc documentation exported markdown documents
 */
export function buildTypeDocCategorySidebar(path: string, label: string): SidebarItemConfig[] {

    const elements = [
        'Classes',
        'Enumerations',
        'Functions',
        'Interfaces',
        'Namespaces',
        'Type Aliases',
        'Variables',
    ];
    const items = elements
    .filter((element) => fs.existsSync(`${path}/${element.toLowerCase()}`))
    .map((element) => {
        return {
            type: 'category',
            label: element,
            link: {
                type: 'generated-index',
                title: element,
                description: element
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: `${path}/${element.toLowerCase()}`,
                },
            ]
        } as SidebarItemConfig
    });

    return [
        {
            type: 'category',
            label,
            link: {
                type: 'doc',
                id: path + '/README',

            },
            items
        }
    ]
}