import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';




const sidebar: SidebarsConfig[keyof SidebarsConfig] = [
    {
        type: 'doc',
        id: 'documentation/learn/README',
    },
    {
        type: 'doc',
        id: 'documentation/learn/introduction',
    },
    {
        type: 'category',
        label: 'Components',
        link: {
            type: 'generated-index',
            title: 'Cloud Agent',
            description: 'Cloud Agent'
        },
        items: [
            {
                type: 'autogenerated',
                dirName: 'documentation/learn/components',
            },

        ]
    },
    {
        type: 'doc',
        id: 'documentation/learn/glossary',
    },
]

export default sidebar
