import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';




const sidebar: SidebarsConfig[keyof SidebarsConfig] = [
    {
        type: 'doc',
        id: 'documentation/learn/README',
    },
    {
        type: 'doc',
        id: 'documentation/learn/what-is-hyperledger-identus',
    },
    {
        type: 'doc',
        id: 'documentation/learn/basic-concepts',
    },
    {
        type: 'category',
        label: 'Community initiatives',
        link: {
            type: 'generated-index',
            title: 'Community initiatives',
            description: 'Funded community projects and real-world deployments.'
        },
        items: [
            {
                type: 'autogenerated',
                dirName: 'documentation/learn/community-initiatives',
            },
        ]
    },
    {
        type: 'category',
        label: 'Advanced explainers',
        link: {
            type: 'generated-index',
            title: 'Advanced explainers',
            description: 'Technical deep-dive documentation for Identus components'
        },
        items: [
            {
                type: 'autogenerated',
                dirName: 'documentation/learn/advanced-explainers',
            },

        ]
    },
    {
        type: 'doc',
        id: 'documentation/learn/glossary',
    },
]

export default sidebar
