import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';


import Sidebar from '../../cloud-agent/docs/docusaurus/sidebars.js'
import { SidebarItemConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

const tutorialsSidebar = Sidebar.tutorialsSidebar as SidebarItemConfig[];

const converted = tutorialsSidebar
    .filter((item) => item !== 'index')
    .map((item) => {
        if (typeof item === 'string') {
            return `cloud-agent/docs/docusaurus/${item}`
        }
        if (item.type === 'category') {
            return {
                ...item,
                items: Array.isArray(item.items) ?
                    item.items.map((item) => `cloud-agent/docs/docusaurus/${item}`) :
                    []
            }
        }
        return item;
    });

const sidebar: SidebarsConfig[keyof SidebarsConfig] = [

    {
        type: 'category',
        label: 'SDKs',
        collapsed: true,
        link: {
            type: 'generated-index',
            title: 'SDKs',
            description: 'SDKs'
        },
        items: [
            {
                type: 'category',
                label: 'Typescript',
                collapsed: true,
                link: {
                    type: 'doc',
                    id: 'sdk-ts/docs/sdk/README',
                },
                items: [
                    {
                        type: 'category',
                        label: 'Tutorials',
                        link: {
                            type: 'generated-index',
                            title: 'Tutorials',
                            description: 'Tutorials'
                        },
                        items: [
                            {
                                type: 'doc',
                                id: 'sdk-ts/docs/examples/Backup',
                                label: 'Backup',
                            },
                            {
                                type: 'doc',
                                id: 'sdk-ts/docs/pluto/README',
                                label: "Storage - Pluto"
                            },
                            {
                                type: 'category',
                                label: 'Prism DID',
                                link: {
                                    type: 'generated-index',
                                    title: 'Prism DID',
                                    description: 'Prism DID Related tutorials and documentation'
                                },
                                items: [
                                    {
                                        type: 'autogenerated',
                                        dirName: 'sdk-ts/docs/prism',
                                    },
                                ]
                            },
                            {
                                type: 'category',
                                label: 'Connectionless & OOB',
                                link: {
                                    type: 'generated-index',
                                    title: 'Connectionless & OOB',
                                    description: 'Connectionless & OOB'
                                },
                                items: [
                                    {
                                        type: 'autogenerated',
                                        dirName: 'sdk-ts/docs/examples/connectionless',
                                    },
                                ]
                            },
                            {
                                type: 'doc',
                                id: 'sdk-ts/docs/examples/SDKVerification',
                                label: "SDK Verification"
                            },
                            {
                                type: 'doc',
                                id: 'sdk-ts/docs/examples/OIDC',
                                label: "OIDC Agent (WIP)"
                            },
                        ]
                    },

                    {
                        type: 'category',
                        label: 'Migration guides',
                        link: {
                            type: 'generated-index',
                            title: 'Migration guides',
                            description: 'Migration guides'
                        },
                        items: [
                            {
                                type: 'autogenerated',
                                dirName: 'sdk-ts/docs/migration',
                            },
                        ]
                    }
                ]
            },
            {
                type: 'link',
                label: 'Swift',
                href: 'https://hyperledger-identus.github.io/sdk-swift/documentation/edgeagentsdk/',
            },
            {
                type: 'link',
                label: 'Kotlin',
                href: 'https://hyperledger-identus.github.io/sdk-kmp/',
            },
        ]
    },
    {
        type: 'category',
        label: 'Cloud Agent',
        collapsed: true,
        link: {
            type: 'generated-index',
            title: 'Cloud Agent',
            description: 'Cloud Agent'
        },
        items: [
            {
                type: 'category',
                label: 'Tutorials',
                link: {
                    type: 'doc',
                    id: 'cloud-agent/docs/docusaurus/index'
                },
                items: [
                    'documentation/developers/quick-start',
                    ...converted
                ]
            },
            {
                type: 'autogenerated',
                dirName: 'documentation/developers/cloud-agent',
            },
        ]
    },

]

export default sidebar