name: Documentation build

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: yarn build
      - name: Save website
        uses: actions/upload-artifact@v2
        with:
          name: build-website
          path: build/
