name: Documentation build

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: identus-documentation-portal

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:  
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.IDENTUS_CI }}
          fetch-depth: 0
          
      - name: Update submodules
        run: |
          git submodule update --remote --recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: |
          yarn build --out-dir infra/website
  release:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'chore(release)')
    uses: ./.github/workflows/release.yml
    secrets: inherit
  deploy:
    if: startsWith(github.ref, 'refs/tags') && contains(github.event.head_commit.message, 'chore(release)')
    uses: ./.github/workflows/deployment.yml
    with:
      version: "${{ github.ref_name }}"
      env: "staging"
    secrets: inherit
