name: Cleanup Package Versions

# This workflow is executed every Monday at 3:00 AM and deletes outdated versions of packages for the current repository.
# GitHub Action actions/delete-package-versions@v4 is used.
# Current retention policy:
# - Keep 10 last packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          owner: ${{ github.repository_owner }}
          package-name: identus-documentation-portal
          package-type: container
          min-versions-to-keep: 10
          token: ${{ secrets.GITHUB_TOKEN }}
