name: Release docs image

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      release-branch:
        description: "Branch to release from"
        required: false
        default: "main"

jobs:
  release:
    env:
      GITHUB_ACTOR: "hyperledger-bot"
      GITHUB_ACTOR_EMAIL: "hyperledger-bot@hyperledger.org"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.IDENTUS_CI }}
          ref: ${{ github.event.inputs.release-branch }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.HYP_BOT_GPG_PRIVATE }}
          passphrase: ${{ secrets.HYP_BOT_GPG_PASSWORD }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          git_tag_gpgsign: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Build ADRs
        run: |
          cd ./identus-cloud-agent
          npm install -g log4brains
          log4brains build --out ../static/adrs --basePath /adrs
          touch ../static/adrs/.nojekyll

      - name: Release
        env:
          GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
          GITHUB_TOKEN: ${{ secrets.IDENTUS_CI }}
        run: |
          npm install
          npx semantic-release

  ghpages:
    name: Deploy gh-pages
    needs: release
    runs-on: ubuntu-latest
    if: (inputs.force_deploy_ghpages == true) || (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/gh-pages-test')
    steps:
      # https://github.com/japgolly/setup-everything-scala
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Needed for the release tag // `git fetch --tags` will also work
      # - name: Setup Java and Scala
      #   uses: olafurpg/setup-scala@v14
      #   with:
      #     java-version: adopt@1.11
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      # - name: Setup Scala.JS
      #   uses: japgolly/setup-scalajs@v1
      # - name: Cache sbt
      #   uses: coursier/cache-action@v6.3

      # ### create build deploy gh-pages ###
      # - name: sbt "docAll; siteAll"
      #   run: sbt -v "docAll; siteAll"

      - name: Build
        run: |
          npm install
          npm build

      - name: Deploy
        # https://github.com/marketplace/actions/github-pages-action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # cname: doc.did.fmgp.app