name: 'Update submodules'

on:
  # Weekly
  schedule:
    - cron: '0 0 * * 0'
  # By manual trigger
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        id: import_gpg
        with:
          gpg-private-key: ${{ secrets.HYP_BOT_GPG_PRIVATE }}
          passphrase: ${{ secrets.HYP_BOT_GPG_PASSWORD }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git_config_global: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.IDENTUS_CI }}
          commit_message: "feat: update submodules documentation to latest"
          commit_user_name: ${{ steps.import_gpg.outputs.name }}
          commit_user_email: ${{ steps.import_gpg.outputs.email }}
          commit_signoff: true
          commit_gpg_sign: true
